name: Step 2 # Explaining legacy code

on:
  push:
    branches:
      - "modernize-legacy-code"
    paths:
      - "docs/*"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-create-test-plan.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v3
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          direction: last

      - name: Update comment - checking work
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
          edit-mode: replace

      # START: Check practical exercise

      - name: Check for an explanation of data.cob
        id: check-explanation-data-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'data.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for an explanation of main.cob
        id: check-explanation-main-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'main.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for an explanation of operations.cob
        id: check-explanation-operations-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'operations.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for a mermaid diagram
        id: check-mermaid-diagram
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'mermaid'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Update comment - step results
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          edit-mode: replace
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 2
            results_table:
              - description: "Check README.md for an explanation of data.cob"
                passed: ${{ steps.check-explanation-data-cob.outcome == 'success' }}
              - description: "Check README.md for an explanation of main.cob"
                passed: ${{ steps.check-explanation-main-cob.outcome == 'success' }}
              - description: "Check README.md for an explanation of operations.cob"
                passed: ${{ steps.check-explanation-operations-cob.outcome == 'success' }}
              - description: "Check README.md for a mermaid diagram"
                passed: ${{ steps.check-mermaid-diagram.outcome == 'success' }}

      # END: Check practical exercise

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1


  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Create comment - step finished
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 3

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_3_FILE }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
